#! /usr/bin/env python

"""
help       -> scons -h
compile    -> scons
clean      -> scons -c
install    -> scons install
uninstall  -> scons -c install
configure  -> scons configure debug=full extraincludes=/usr/local/include:/tmp/include prefix=/usr/local

Run from a subdirectory -> scons -u (or export SCONSFLAGS="-u" in your ~/.bashrc)

"""

###################################################################
# LOAD THE ENVIRONMENT AND SET UP THE TOOLS
###################################################################
import sys, os
sys.path.append('scons_admin')

## Import the main configuration tool
from generic import configure
config = {
	'modules'  : 'generic kde3 midi',
	'builddir' : './',
	'config.h' : 0,
	'rpath'    : 1,
	'colorful' : not os.environ.has_key('NOCOLORS'),
}

# and the config.h
env=configure(config)

## Load the builders in config
#env = Environment( TARGS=COMMAND_LINE_TARGETS, ARGS=ARGUMENTS, tools=['default', 'generic', 'kde','midi'], toolpath=['./', './scons_admin'])

env.KDEuse("environ rpath thread")

###################################################################
# SCRIPTS FOR BUILDING THE TARGETS
###################################################################

# NoteEdit Version
version = '2.8.1'
env.AppendUnique( CPPFLAGS = ['-DVERSION=\\\"'+version+'\\\"'])

# Flag so we don't include config.h if compiled with scons
# This will be removed as soon as automake support is removed
env.AppendUnique( CPPFLAGS = ['-DWITH_SCONS'])
# Assume we have at least gcc-3.x for scons (i.e. deprecated)
# This compiler specific flag will be removed from the source
env.AppendUnique( CPPFLAGS = ['-DGCC_MAJ_VERS=3'])

## BuilDir example - try to have all sources to process in only one top-level folder
env.set_build_dir('#build', '#kguitar_excerpt #noteedit #doc')
env.subdirs('kguitar_excerpt noteedit po doc')

###################################################################
# CONVENIENCE FUNCTIONS TO EMULATE 'make dist' and 'make distclean'
###################################################################

env.dist('noteedit','2.8.1')
