############################
## load the config

## use the environment set in the top-level
## SConstruct file (IMPORTANT)

Import( 'env' )
import os

###################################################################
# Copy necessary ui files
###################################################################

# QT2 is no longer supported, so we ignore these files
# If we add QT4 support we should add again have two files
# for the KDE3 and QT4 and handle the file type (".qt4") correctly
# Therefore kde_version / qt_version needs to be exported from kde.py!
if( not os.path.isfile('lyrics.ui') ):
    env.Execute(Copy('lyrics.ui', 'lyrics.ui.qt3'))

# Define the Prefix for our lex / grammar
LEX_PREFIX  = 'NEDIT'
# Variables for compiling lex / grammar file
LEX_RESTART = LEX_PREFIX + 'restart'
LEX_LINENO  = LEX_PREFIX + 'lineno'
YACC_PARSE  = LEX_PREFIX + 'parse'
YACC_LVAL   = LEX_PREFIX + 'lval'
PREFIX_DEF='-DYYLINENO=' + LEX_LINENO + ' -DYYRESTART=' + LEX_RESTART + \
           ' -DYYPARSE=' + YACC_PARSE + ' -DYYLVAL='    + YACC_LVAL

# Compiling the lex file
# Compiling the grammar file
# remove from sourcesr
# Variant 1: add manual command for these files with env.Command

# env.Command('lexik.cpp', 'lexik.ll',
#             "$CPPLEXBUILD < $SOURCES > $TARGET")
# env.Command('grammar.cpp', 'grammar.yy',
#             "$CPPLEXBUILD < $SOURCES > $TARGET")
# CPPLEXBUILD = $CPPBUILD + CPPFLAGS=PREFIX_DEF or similar

# Variant 2: add the flags to the static object lexik.ll / grammar.yy

# Create new environment for extra CPPFLAGS not added to other files
envlex = env.Copy()
envlex.Append( CPPFLAGS = PREFIX_DEF )
# StaticObect does return an object not being a string, so we need to convert it first
# Create a separate string list from these to objects, we will add it later to the sources
LG = str(envlex.StaticObject("grammar.yy", CPPFLAGS='${CPPFLAGS}',
                             YACCFLAGS='-y -d -pNEDIT')[0]) + ' ' + \
     str(envlex.StaticObject("lexik.ll", CPPFLAGS='${CPPFLAGS}',
                             LEXFLAGS='-l -PNEDIT')[0]) + ' ' + \
     str(envlex.StaticObject("filehandler.cpp", CPPFLAGS = '${CPPFLAGS}',
                             LEXFLAGS='-l -PNEDIT')[0])
# More special compile flags for other files (environments) should be added here.

# Currently left out: Special flags for final (Hide Exceptions from TSE3)

# Our source files
sources = """
abcexport.cpp 
abcexportform.ui
chord.cpp 
chorddiagram.cpp
clef.cpp
configuredialog.cpp 
dbufferwidget.cpp 
exports.ui 
expWarn.ui
filter.ui
generProps.ui 
internals.cpp
keyoffs.cpp 
keysig.cpp 
layout.cpp
lilyexport.cpp 
lilypondexportform.ui
lilytest.cpp 
lines.ui 
listSel.ui 
lyrics.ui
mainframewidget2.cpp 
mainframewidget.cpp 
metronom.ui
mididevicelistbox.cpp 
midiexport.cpp 
midiexportform.ui 
midimapper.cpp
miditimescale.cpp
midi.ui 
mupWarning.ui 
multistaffinfo.cpp
muselement.cpp 
musicxmlexportform.ui
musicxmlcommon.cpp
musicxmlimport.cpp
musicxmlexport.cpp
musixtex.cpp 
musixtexexportform.ui 
noteedit_part.cpp 
notesel.cpp 
numberdisplay.cpp
outputbox.cpp 
pmxexportform.ui
pmxexport.cpp 
previewprint.cpp
saveparametersform.ui
resource.cpp 
rest.cpp
scaleedit.ui
scaleEd.ui 
ScoreEditor.cpp 
scoreinfo.cpp 
sign.cpp
smRest.ui 
staff.cpp 
staffElem.ui 
staffPropFrm.cpp 
staffProps.ui 
staffSel.ui
text.cpp 
textDialog.ui 
textDialog_impl.cpp
tempotrack.cpp 
timesig.cpp 
timesigDia.ui 
tip.ui
transpainter.cpp 
tse3handler.cpp 
tse3Info.ui 
tupletdialog.ui
tupletdialog_impl.cpp 
scaleedit_impl.cpp 
uiconnect.cpp
voice.cpp 
voicedialog.cpp 
voiceDia.ui 
volume.ui
zoomselection.cpp 
"""

# Make a list of words from the string list
NT = Split( sources )
# Add the LG list to the sources list in the same way
NT = NT + Split(LG)
# print "NT: ", NT, "LG: ", LG

env.KDEstaticlib("noteedit", NT)

env.KDEshlib("noteedit", NT )

env.KDEprogram('noteedit','main.cpp','','./libnoteedit.so','../kguitar_excerpt/libkguitar_excerpt.a',['kparts','kdeprint','tse3'])
