############################
## load the config

## use the environment set in the top-level
## SConstruct file (IMPORTANT)

Import( 'env' )

sources="""
chord.cpp
chordlist.cpp
chordlistitem.cpp
fingerlist.cpp
fingers.cpp
tabcolumn.cpp
tabtrack.cpp
"""

env.KDEstaticlib("kguitar_excerpt", sources)

env.KDEshlib("kguitar_excerpt",sources)
